version: '3.8'

services:
  # Service for the accountract front
  accountract-front:
    build: .
    container_name: accountract-front
    # command: "node .app/.output/server/index.mjs"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.app/node_modules
      - /usr/src/app/.demo/node_modules
      - /usr/src/app/.app/.nuxt
      - /usr/src/app/.app/.output
      - /usr/src/app/.demo/.nuxt
    ports:
      - "3000:3000"
    networks:
      - accountract-network
    restart: always

  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/cert.pem:/etc/ssl/cert.pem
      - /etc/ssl/key.pem:/etc/ssl/key.pem
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - accountract-front
    networks:
      - accountract-network
    restart: always

networks:
  accountract-network:
    driver: bridge

volumes:
  redis_data:
  gpt-db-data:
