services:
  
  
  # Service for the accountract front
  accountract-front:
    build: .
    container_name: accountract-front
    # command: "node .app/.output/server/index.mjs"
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.app/node_modules
      - /usr/src/app/.demo/node_modules
      - /usr/src/app/.app/.nuxt
      - /usr/src/app/.app/.output
      - /usr/src/app/.demo/.nuxt
    ports:
      - "80:3000"
    networks:
      - accountract-network
    restart: always

networks:
  accountract-network:
    driver: bridge



  redis_data:

  # Volume for gpt database data
  gpt-db-data: